edition                     = "2021"
version                     = "Two"
unstable_features           = true
group_imports               = "StdExternalCrate"
imports_layout              = "HorizontalVertical"
imports_granularity         = "Crate"
format_code_in_doc_comments = true
use_field_init_shorthand    = true
