packages:
  - packages/*

minimumReleaseAge: 4320 # 3 days in minutes

minimumReleaseAgeExclude:
  - "esbuild"
  - "@esbuild/*"

catalog:
    '@types/node': 25.2.0
    typescript: 5.9.3
    vitest: 4.0.18
    '@vitest/ui': 4.0.18
    '@vitest/coverage-v8': 4.0.18
    '@vitest/browser-playwright': 4.0.18
