name: Build

on:
  push:
    branches: [main]
    paths-ignore:
      - '*.md'
      - '*.txt'
  pull_request:
    paths-ignore:
      - '*.md'
      - '*.txt'

env:
  CARGO_TERM_COLOR: always

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Cache Cargo dependencies
        uses: actions/cache/save@v3
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Check all packages
        run: cargo check --workspace

  lint:
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore cached Cargo dependencies
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Check the formatting
        run: cargo fmt --all -- --check

      - name: Check the lints
        run: cargo clippy -- -D warnings

  test:
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore cached Cargo dependencies
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run tests
        run: cargo tarpaulin --ignore-tests --out Xml --output-dir target/tarpaulin

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./target/tarpaulin/cobertura.xml
          verbose: true
          fail_ci_if_error: true

  build-core:
    needs:
      - lint
      - test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore cached Cargo dependencies
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build library in release mode
        run: cargo build --lib --release

  build-wasm:
    needs:
      - lint
      - test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [18.x]
    defaults:
      run:
        working-directory: ./packages/auto-palette
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore cached Cargo dependencies
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'
          cache-dependency-path: 'packages/auto-palette/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Build the WASM package
        run: pnpm wasm:web

      - name: Check the lints
        run: pnpm lint

      - name: Build the JS package
        run: pnpm build
